[package]
name = "api"
version = "0.1.0"
authors = ["tpywao <tpywao@gmail.com>"]

[dependencies]
iron = ">=0.5, <0.7"

serde = "*"
serde_json = "*"
serde_derive = "*"

ws = {version="*", features=["ssl"]}
url = "1.5"
openssl = "0.9.24"

hmac = "0.5"
sha2 = "0.7"
